// <auto-generated />
using System;
using System.Collections.Generic;
using Gcs.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gcs.Persistence.Migrations
{
    [DbContext(typeof(GcsDbContext))]
    [Migration("20261007193639_AddOutboxTraceParent")]
    partial class AddOutboxTraceParent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gcs")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gcs.Domain.Commands.CommandAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("callsign");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("command");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("detail");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("operator");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("Parameters")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parameters");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id")
                        .HasName("pk_command_audit");

                    b.HasIndex("VehicleId", "RequestedAt")
                        .HasDatabaseName("ix_command_audit_vehicle_time");

                    b.ToTable("command_audit", "gcs");
                });

            modelBuilder.Entity("Gcs.Domain.Missions.Mission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_missions");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_missions_updated_at");

                    b.ToTable("missions", "gcs");
                });

            modelBuilder.Entity("Gcs.Domain.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("token_hash")
                        .IsFixedLength();

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user");

                    b.ToTable("refresh_tokens", "gcs");
                });

            modelBuilder.Entity("Gcs.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FailedLogins")
                        .HasColumnType("integer")
                        .HasColumnName("failed_logins");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_users_username");

                    b.ToTable("users", "gcs");
                });

            modelBuilder.Entity("Gcs.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autopilot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("autopilot");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("callsign");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("LinkRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("link_requested");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<short>("SystemId")
                        .HasColumnType("smallint")
                        .HasColumnName("system_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Connection", "Gcs.Domain.Vehicles.Vehicle.Connection#ConnectionSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("BaudRate")
                                .HasColumnType("integer")
                                .HasColumnName("connection_baud_rate");

                            b1.Property<string>("Host")
                                .HasMaxLength(253)
                                .HasColumnType("character varying(253)")
                                .HasColumnName("connection_host");

                            b1.Property<int?>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("connection_port");

                            b1.Property<string>("SerialPortName")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("connection_serial_port_name");

                            b1.Property<string>("Transport")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("connection_transport");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Callsign")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_callsign_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("SystemId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_system_id_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("vehicles", "gcs");
                });

            modelBuilder.Entity("Gcs.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "gcs");
                });

            modelBuilder.Entity("Gcs.Persistence.Telemetry.TelemetrySampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<double?>("AirSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("air_speed");

                    b.Property<double?>("AltitudeMsl")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_msl");

                    b.Property<bool?>("Armed")
                        .HasColumnType("boolean")
                        .HasColumnName("armed");

                    b.Property<double?>("BatteryCurrent")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_current");

                    b.Property<int?>("BatteryRemainingPercent")
                        .HasColumnType("integer")
                        .HasColumnName("battery_remaining_percent");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_voltage");

                    b.Property<double?>("ClimbRate")
                        .HasColumnType("double precision")
                        .HasColumnName("climb_rate");

                    b.Property<string>("FlightMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flight_mode");

                    b.Property<string>("GpsFix")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gps_fix");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("ground_speed");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision")
                        .HasColumnName("heading");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("Pitch")
                        .HasColumnType("double precision")
                        .HasColumnName("pitch");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double?>("RelativeAltitude")
                        .HasColumnType("double precision")
                        .HasColumnName("relative_altitude");

                    b.Property<double?>("Roll")
                        .HasColumnType("double precision")
                        .HasColumnName("roll");

                    b.Property<int?>("SatellitesVisible")
                        .HasColumnType("integer")
                        .HasColumnName("satellites_visible");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<double?>("Yaw")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_samples");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_telemetry_samples_time");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .HasDatabaseName("ix_telemetry_samples_vehicle_time");

                    b.ToTable("telemetry_samples", "gcs");
                });

            modelBuilder.Entity("Gcs.Domain.Missions.Mission", b =>
                {
                    b.OwnsMany("Gcs.Domain.Missions.MissionItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("MissionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("Altitude");

                            b1.Property<string>("Command")
                                .IsRequired();

                            b1.Property<double?>("HoldSeconds");

                            b1.Property<double?>("Latitude");

                            b1.Property<double?>("Longitude");

                            b1.Property<double?>("Speed");

                            b1.HasKey("MissionId", "__synthesizedOrdinal");

                            b1.ToTable("missions", "gcs");

                            b1
                                .ToJson("items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MissionId")
                                .HasConstraintName("fk_missions_missions_mission_id");
                        });

                    b.OwnsOne("Gcs.Domain.Missions.MissionUpload", "LastUpload", b1 =>
                        {
                            b1.Property<Guid>("MissionId");

                            b1.Property<DateTimeOffset>("At");

                            b1.Property<string>("Error");

                            b1.Property<bool>("Succeeded");

                            b1.Property<Guid>("VehicleId");

                            b1.HasKey("MissionId");

                            b1.ToTable("missions", "gcs");

                            b1
                                .ToJson("last_upload")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MissionId")
                                .HasConstraintName("fk_missions_missions_id");
                        });

                    b.Navigation("Items");

                    b.Navigation("LastUpload");
                });

            modelBuilder.Entity("Gcs.Domain.Users.RefreshToken", b =>
                {
                    b.HasOne("Gcs.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
