// <auto-generated />
using System;
using System.Collections.Generic;
using Gcs.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gcs.Persistence.Migrations
{
    [DbContext(typeof(GcsDbContext))]
    [Migration("20261006230236_InitialVehicles")]
    partial class InitialVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gcs")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gcs.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autopilot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("autopilot");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("callsign");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<short>("SystemId")
                        .HasColumnType("smallint")
                        .HasColumnName("system_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Connection", "Gcs.Domain.Vehicles.Vehicle.Connection#ConnectionSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("BaudRate")
                                .HasColumnType("integer")
                                .HasColumnName("connection_baud_rate");

                            b1.Property<string>("Host")
                                .HasMaxLength(253)
                                .HasColumnType("character varying(253)")
                                .HasColumnName("connection_host");

                            b1.Property<int?>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("connection_port");

                            b1.Property<string>("SerialPortName")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("connection_serial_port_name");

                            b1.Property<string>("Transport")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("connection_transport");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Callsign")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_callsign_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("SystemId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_system_id_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("vehicles", "gcs");
                });

            modelBuilder.Entity("Gcs.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "gcs");
                });
#pragma warning restore 612, 618
        }
    }
}
