// <auto-generated />
using System;
using System.Collections.Generic;
using Gcs.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gcs.Persistence.Migrations
{
    [DbContext(typeof(GcsDbContext))]
    [Migration("20261007103835_AddVehicleLinkRequested")]
    partial class AddVehicleLinkRequested
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gcs")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gcs.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autopilot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("autopilot");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("callsign");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("LinkRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("link_requested");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<short>("SystemId")
                        .HasColumnType("smallint")
                        .HasColumnName("system_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Connection", "Gcs.Domain.Vehicles.Vehicle.Connection#ConnectionSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("BaudRate")
                                .HasColumnType("integer")
                                .HasColumnName("connection_baud_rate");

                            b1.Property<string>("Host")
                                .HasMaxLength(253)
                                .HasColumnType("character varying(253)")
                                .HasColumnName("connection_host");

                            b1.Property<int?>("Port")
                                .HasColumnType("integer")
                                .HasColumnName("connection_port");

                            b1.Property<string>("SerialPortName")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("connection_serial_port_name");

                            b1.Property<string>("Transport")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("connection_transport");
                        });

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("Callsign")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_callsign_active")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("SystemId")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_system_id_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("vehicles", "gcs");
                });

            modelBuilder.Entity("Gcs.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "gcs");
                });

            modelBuilder.Entity("Gcs.Persistence.Telemetry.TelemetrySampleRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<double?>("AirSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("air_speed");

                    b.Property<double?>("AltitudeMsl")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_msl");

                    b.Property<bool?>("Armed")
                        .HasColumnType("boolean")
                        .HasColumnName("armed");

                    b.Property<double?>("BatteryCurrent")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_current");

                    b.Property<int?>("BatteryRemainingPercent")
                        .HasColumnType("integer")
                        .HasColumnName("battery_remaining_percent");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_voltage");

                    b.Property<double?>("ClimbRate")
                        .HasColumnType("double precision")
                        .HasColumnName("climb_rate");

                    b.Property<string>("FlightMode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("flight_mode");

                    b.Property<string>("GpsFix")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gps_fix");

                    b.Property<double?>("GroundSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("ground_speed");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision")
                        .HasColumnName("heading");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("Pitch")
                        .HasColumnType("double precision")
                        .HasColumnName("pitch");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<double?>("RelativeAltitude")
                        .HasColumnType("double precision")
                        .HasColumnName("relative_altitude");

                    b.Property<double?>("Roll")
                        .HasColumnType("double precision")
                        .HasColumnName("roll");

                    b.Property<int?>("SatellitesVisible")
                        .HasColumnType("integer")
                        .HasColumnName("satellites_visible");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<double?>("Yaw")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_samples");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_telemetry_samples_time");

                    b.HasIndex("VehicleId", "RecordedAt")
                        .HasDatabaseName("ix_telemetry_samples_vehicle_time");

                    b.ToTable("telemetry_samples", "gcs");
                });
#pragma warning restore 612, 618
        }
    }
}
