<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gcs.Telemetry</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Gcs.Application/Gcs.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Gcs.UnitTests" />
  </ItemGroup>

</Project>
