"""Generates reference MAVLink v2 frames with pymavlink (the reference implementation maintained by the MAVLink project).

Our C# codec is tested against these bytes, so a mistake in field order, scaling, CRC_EXTRA or payload truncation
fails a test instead of failing in the air.

Usage:
    python -m venv .venv && .venv/Scripts/pip install pymavlink   (Linux/macOS: .venv/bin/pip)
    .venv/Scripts/python scripts/generate-mavlink-golden.py > tests/Gcs.UnitTests/Mavlink/GoldenFrames.g.cs
"""
from pymavlink.dialects.v20 import common as mavlink2

SYSTEM_ID = 1
COMPONENT_ID = 1


class _Sink:
    def write(self, data):
        pass


def frame(build, seq):
    mav = mavlink2.MAVLink(_Sink(), srcSystem=SYSTEM_ID, srcComponent=COMPONENT_ID)
    mav.seq = seq
    return build(mav).pack(mav)


CASES = [
    ("Heartbeat", lambda m: m.heartbeat_encode(
        mavlink2.MAV_TYPE_QUADROTOR, mavlink2.MAV_AUTOPILOT_PX4,
        mavlink2.MAV_MODE_FLAG_SAFETY_ARMED | mavlink2.MAV_MODE_FLAG_CUSTOM_MODE_ENABLED,
        (4 << 16) | (3 << 24), mavlink2.MAV_STATE_ACTIVE, 3)),
    ("HeartbeatGcs", lambda m: m.heartbeat_encode(
        mavlink2.MAV_TYPE_GCS, mavlink2.MAV_AUTOPILOT_INVALID, 0, 0, mavlink2.MAV_STATE_ACTIVE, 3)),
    # Note: *_encode takes fields in XML definition order; the wire order (sorted by type size) differs.
    ("SysStatus", lambda m: m.sys_status_encode(
        0, 0, 0, 250, 15800, 1234, 76, 0, 0, 0, 0, 0, 0)),
    ("GpsRawInt", lambda m: m.gps_raw_int_encode(
        123456789, 3, 399250000, 328540000, 950000, 120, 180, 1250, 9000, 14)),
    ("Attitude", lambda m: m.attitude_encode(
        65000, 0.1, -0.05, 1.5707964, 0.01, 0.02, -0.03)),
    ("GlobalPositionInt", lambda m: m.global_position_int_encode(
        65000, 399250000, 328540000, 950000, 50000, 1200, -300, -50, 9000)),
    ("VfrHud", lambda m: m.vfr_hud_encode(13.5, 12.25, 90, 55, 950.0, -0.5)),
    ("CommandLong", lambda m: m.command_long_encode(
        1, 1, mavlink2.MAV_CMD_COMPONENT_ARM_DISARM, 0, 1, 0, 0, 0, 0, 0, 0)),
    ("CommandAck", lambda m: m.command_ack_encode(mavlink2.MAV_CMD_COMPONENT_ARM_DISARM, mavlink2.MAV_RESULT_ACCEPTED)),
    # Mission protocol (Phase 6). mission_type extension fields are left at 0 (mission), so they are truncated.
    ("MissionRequestList", lambda m: m.mission_request_list_encode(1, 1)),
    ("MissionCount", lambda m: m.mission_count_encode(1, 1, 5)),
    ("MissionRequestInt", lambda m: m.mission_request_int_encode(255, 190, 3)),
    ("MissionItemInt", lambda m: m.mission_item_int_encode(
        1, 1, 2, mavlink2.MAV_FRAME_GLOBAL_RELATIVE_ALT_INT, mavlink2.MAV_CMD_NAV_WAYPOINT, 0, 1,
        5.0, 2.0, 0.0, float("nan"), 399255330, 328662870, 120.0)),
    ("MissionAck", lambda m: m.mission_ack_encode(255, 190, mavlink2.MAV_MISSION_ACCEPTED)),
    ("MissionAckInvalidSequence", lambda m: m.mission_ack_encode(255, 190, mavlink2.MAV_MISSION_INVALID_SEQUENCE)),
    ("MissionCurrent", lambda m: m.mission_current_encode(2)),
    ("MissionItemReached", lambda m: m.mission_item_reached_encode(2)),
]

print("// <auto-generated> by scripts/generate-mavlink-golden.py with pymavlink. Do not edit by hand. </auto-generated>")
print("namespace Gcs.UnitTests.Mavlink;")
print()
print("internal static class GoldenFrames")
print("{")
for seq, (name, build) in enumerate(CASES):
    data = frame(build, seq)
    print(f"    public static readonly byte[] {name} = [{', '.join(f'0x{b:02X}' for b in data)}];")
print("}")
print()
print()
print("// Message metadata from pymavlink: wire field order and CRC_EXTRA")
for name in ["HEARTBEAT", "SYS_STATUS", "GPS_RAW_INT", "ATTITUDE", "GLOBAL_POSITION_INT", "VFR_HUD", "COMMAND_LONG", "COMMAND_ACK",
             "MISSION_REQUEST_LIST", "MISSION_COUNT", "MISSION_REQUEST_INT", "MISSION_ITEM_INT", "MISSION_ACK",
             "MISSION_CURRENT", "MISSION_ITEM_REACHED"]:
    cls = getattr(mavlink2, f"MAVLink_{name.lower()}_message")
    print(f"// {name}: id={cls.id} crc_extra={cls.crc_extra} wire_order={cls.ordered_fieldnames}")
